### ISSUE TITLE
Mobile:: Captcha not accessible over some networks.

### ISSUE THREAD

**Issue by JohnRSim** [JSEcoin/platform#1]
Some public networks block core jsecoin.com domain.
However allow platform.jsecoin.com

If this is the case the following issue will appear -
![screenshot_20180527-134046](https://user-images.githubusercontent.com/364208/40602824-ea844df0-6251-11e8-8c39-e91f1e5db77c.jpg)

Need to be able to confirm access to domains.

**Comment by key2peace** [comment]
- copy/move stuff to platform.* (I think it belongs there anyway)
- perform a simple hit test when needed, perhaps put it in settings, if ppl have issues, have them hit the 'test connectivity') which will determine the path.
- make platform dualstacked (add ipv6), if the filter is v4 based, v6 will solve this

**Comment by JohnRSim** [comment]
Thanks we plan to implement in the next release 0.5.3
