### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by Jeroenleender** [JSEcoin/platform#10]
Installed latest alpha version on android device.

When using email and password which i can use on the platform and which work.
It says;

Error:
Failed to submit form - please check all required fields

There are only 2 fields...
login and password...

What todo to make this working?

**Comment by JohnRSim** [comment]
Which version number? 
Please use https://github.com/JSEcoin/platform/releases/tag/v0.5.8-alpha 

- a new release is coming out next week that will have a number of fixes.

**Comment by Jeroenleender** [comment]
I First tried v0.5.9-beta
I could login then but the button to mine wasn't working. I then received a message in the app that i had to confirm my email, which i alrdy did 2 days ago. So i removed that version and installed  v0.5.8-alpha, i even rebooted my phone. But no matter what i do i can't login anymore, i attached the screenshot.
![Screenshot_20190829-145615_JSECoin](https://user-images.githubusercontent.com/47397626/63942112-55b9d980-ca6d-11e9-90c2-f54d9bad66d1.jpg)
