### ISSUE TITLE
I First tried v0.5.9-beta

### ISSUE THREAD

**Issue by Jeroenleender** [JSEcoin/platform#11]
I First tried v0.5.9-beta
I could login then but the button to mine wasn't working. I then received a message in the app that i had to confirm my email, which i alrdy did 2 days ago. So i removed that version and installed  v0.5.8-alpha, i even rebooted my phone. But no matter what i do i can't login anymore, i attached the screenshot.
![Screenshot_20190829-145615_JSECoin](https://user-images.githubusercontent.com/47397626/63942112-55b9d980-ca6d-11e9-90c2-f54d9bad66d1.jpg)

_Originally posted by @Jeroenleender in https://github.com/JSEcoin/platform/issues/10#issuecomment-526172899_

**Comment by JohnRSim** [comment]
unable to replicate.
