### ISSUE TITLE
Mining button doesn't work on 0.5.9 Android

### ISSUE THREAD

**Issue by kabob8933** [JSEcoin/platform#12]
On the alpha 0.5.9, when the mining button is pressed, the text color changes from black to white, but it doesn't actually mine. Also, the Background Support slider will slide, but when you go to another tab and then back, it has turned itself off. I am using a Samsung Galaxy A20 with Android 9 Pie.

**Comment by kabob8933** [comment]
Screen recording here: https://drive.google.com/file/d/1SIbYVbckHbxULZ_XNXh7MeXsTQy4cBk0/view?usp=drivesdk

**Comment by kabob8933** [comment]
Screen recording here: 
https://drive.google.com/file/d/1-65dO7NcQCQzkQtbrsUJVnA575e_UjQV/view?usp=drivesdk

**Comment by JohnRSim** [comment]
Thanks this issue has now been resolved and will be available in the next release.
