### ISSUE TITLE
Android app - confirm email

### ISSUE THREAD

**Issue by MegaLite** [JSEcoin/platform#18]
Only when you select the "Background support" option in the settings, the next time you start the application, a proposal to confirm your email, which is crap in the edge, is displayed. This bug wanders from release to release, fix it finally!

(Translated by Google)

**Comment by JohnRSim** [comment]
Which version are you currently running? Please goto settings and take a screenshot I believe all of these issues have been resolved with the latest release.

**Comment by MegaLite** [comment]
LATEST. From this URL: https://github.com/JSEcoin/platform/releases

![Screenshot_20191126-194913](https://user-images.githubusercontent.com/33813016/69655044-d6956b00-1086-11ea-8d7b-9c94df961fd1.png)
![Screenshot_20191126-195109](https://user-images.githubusercontent.com/33813016/69655045-d6956b00-1086-11ea-93ed-2961d92ddcc1.png)

**Comment by JohnRSim** [comment]
We have found the issue and is now fixed and will be out with the next release 0.6.7

**Comment by MegaLite** [comment]
Ok, thanks!

**Comment by RayPylant** [comment]
I still can not operate or get an email sent from this platform. tried 19 times so reverted back to stand alone CPU site browser. Is there a fix yet.
