### ISSUE TITLE
unable to register account on website

### ISSUE THREAD

**Issue by gainmedia** [JSEcoin/platform#19]
Hi, I am unable to register as your captcha code hovers in space ... and the page does not continue ... 
how do I go about this as I've tried firefox and Chrome .... please don't tell me I have to use IE ... I would probably die.

**Comment by JohnRSim** [comment]
Could you share a screenshot

**Comment by gainmedia** [comment]
![Capture](https://user-images.githubusercontent.com/36214758/69640150-8e665080-1066-11ea-91f8-2cbdaa88ebc0.PNG)

**Comment by gainmedia** [comment]
It stays on that - the indicator just keeps running and the page load is incomplete.

**Comment by JohnRSim** [comment]
Do you have any ad blockers looks as if connection can't successfully be made to the captcha server.
