### ISSUE TITLE
visual notifications bug

### ISSUE THREAD

**Issue by jamesbachini** [JSEcoin/platform#21]
This is on visual notifications on the settings page.

I'm getting the same thing where it's not storing the toggle switch state. The email notifications and newsletter settings below it are working fine. 

Had a quick look at the code and it's related to this var:-
this.$store.state.app.notifications

There's some logic at line 258 in /src/views/settings/Settings-Page.vue that might be causing it.

**Comment by JohnRSim** [comment]
Will review and fix this week
