### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by githubquestion12** [JSEcoin/platform#6]
Hi, I am trying to use the app to mine however it keeps saying connection failed, retrying in X seconds. I have 4 bars of Wifi on my laptop, any reason why this could be the case?

**Comment by JohnRSim** [comment]
Antivirus or malware app may be blocking connection to our server - try disabling and letting us know what is blocking it and we will connect with the team and get jsecoin whitelisted as we get bundled in with monero high process miners which we are not.

Thanks
J

**Comment by githubquestion12** [comment]
Hi, I'm not sure what is blocking it - I also sent a message on discord

**Comment by JohnRSim** [comment]
In the next release - 0.5.3 we will detect any network issues that may be blocked by third parties and will announce this from within the app.
