### ISSUE TITLE
MacOS Platform Miner has slower hash rate than in-browser miner when using the same settings

### ISSUE THREAD

**Issue by j3py** [JSEcoin/platform#7]
I recently found that the Mac OS platform miner version 0.5.8a with the mining acceleration setting set to 9 averages around 9200 H/s (see below for my machine's specs).  Where as, in the latest stable version of Chrome if I go to platform.jsecoin.com and mine from there with the same mining acceleration setting it averages around 9700 H/s.  Interestingly, when I boot into Windows 10 via bootcamp, and use the platform miner version 0.5.8a for Windows I average around 9900 H/s.

Anyway, I just wanted to highlight this issue in case it hasn't been considered before.  I understand that it can be difficult or even impossible in some cases to bring each platform to parity.

My machine's specs:
Processor: 2.6 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 4000 1536 MB
OS: macOS High Sierra v.10.13.6 and Windows 10

**Comment by JohnRSim** [comment]
Thanks for bringing this up! 👍 
Unfortunately I can't do anything with increasing the performance. 
Ideally minimum hashrate you need is around 3,000 H/s

**Comment by AllenChong** [comment]
issue
